theme: jekyll-theme-cayman
show_downloads: "true"
github:
  repository_name: "VR Toolkit"
  zip_url: https://github.com/retroluxfilm/reshade-vrtoolkit/releases/download/v0.9.2-pre/VRToolkitReshadeUniversal_0.9.2-pre.zip

logo: /assets/vrtoolkit_logo.png
