theme: jekyll-theme-cayman
show_downloads: "true"
github:
  repository_name: "VR Toolkit"
  zip_url: https://github.com/retroluxfilm/reshade-vrtoolkit/releases/download/v0.9.2-pre/VRToolkitReshadeUniversal_0.9.2-pre.zip
logo: /assets/vrtoolkit_logo.png
image: https://repository-images.githubusercontent.com/376497253/bd2d3180-ccb3-11eb-90fa-95ec63cea508 